pub enum BuiltinPkgFunctions {
    NavigateToUrl,
    GetElementByText,
    GetElementByTextExact,
    GetElementByString,
    GetElementByStringExact,
    ClickElementByText,
    ClickElementByTextExact,
    ClickElementByString,
    ClickElementByStringExact,
    SendTextToElementByText,
    SendTextToElementByTextExact,
    SendTextToElementByString,
    SendTextToElementByStringExact,
    GetInputFromLabel,
    GetIFrameFromLabel,
    GetWindowFromLabel,
    GetGroupFromLabel,
    InputDateByLabelExact,
    InputHtmlByLabelExact,
    InputNumberTextboxByLabelExact,
    InputTextboxByLabelExact,
    InputDropdownUsingTextByLabelExact,
    InputDropdownUsingIndexByLabelExact,
    InputRadioUsingTextByLabelExact,
    InputRadioUsingIndexByLabelExact,
    GetAndSwitchToAnyIFrame,
    GetAndSwitchToParentIFrame,
    GetAndSwitchToRootIFrame,
}

pub enum BuiltinPkgVariables {}
