# This is a basic workflow to help you get started with Actions
name: Rust CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  BuildWasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: "wasm32-unknown-unknown"
          override: true
      - name: Download wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
      - run: wasm-pack build
      - run: wasm-pack test --chrome --firefox --headless

  CheckBeta:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        runconfig: [
          'check',
          'check --target wasm32-unknown-unknown',
          'check                                 --no-default-features',
          'check --target wasm32-unknown-unknown --no-default-features',
          'check                                 --no-default-features --features console_error_panic_hook',
          'check --target wasm32-unknown-unknown --no-default-features --features console_error_panic_hook',
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Install latest beta
        uses: actions-rs/toolchain@v1
        with:
            toolchain: beta
            target: "wasm32-unknown-unknown"
            override: true
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.runconfig }}
          
  CheckNightly:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        runconfig: [
          'check',
          'check --target wasm32-unknown-unknown',
          'check                                 --no-default-features',
          'check --target wasm32-unknown-unknown --no-default-features',
          'check                                 --no-default-features --features console_error_panic_hook',
          'check --target wasm32-unknown-unknown --no-default-features --features console_error_panic_hook',
          'check                                 --no-default-features --features "console_error_panic_hook wee_alloc"',
          'check --target wasm32-unknown-unknown --no-default-features --features "console_error_panic_hook wee_alloc"',
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            target: "wasm32-unknown-unknown"
            override: true
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: ${{ matrix.runconfig }}